LondonBicycles:
  outputs:
    dev:
      dataset: LondonBicycles
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: US
      method: service-account
      priority: interactive
      project: "{{ env_var('DSAI_PROJECT_ID') }}"
      threads: 1
      type: bigquery
  target: dev